### ISSUE TITLE
ArrayIndexOutOfBoundsException in PStack.pop

### ISSUE THREAD

**Issue by mro** [piccolo2d/piccolo2d.java#240]
Originally reported on Google Code with ID 240
```
I'm seeing this occasionally in my LD#24 entry, which uses piccolo2d svn trunk

Exception in thread "Animation Thread"
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.remove(ArrayList.java:390)
	at org.piccolo2d.util.PStack.pop(PStack.java:84)
	at org.piccolo2d.util.PPaintContext.popTransform(PPaintContext.java:261)
	at org.piccolo2d.PCamera.paint(PCamera.java:350)
	at org.piccolo2d.PNode.fullPaint(PNode.java:2757)
	at org.piccolo2d.PCamera.fullPaint(PCamera.java:439)
	at org.piccolo2d.POffscreenCanvas.render(POffscreenCanvas.java:104)
	at org.piccolo2d.processing.Piccolo2D.draw(Piccolo2D.java:96)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1078)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1071)
	at processing.core.PApplet.handleDraw(PApplet.java:2003)
	at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:186)
	at processing.core.PApplet.run(PApplet.java:1867)
	at java.lang.Thread.run(Thread.java:662)


The other things in the stack trace are a Processing library wraps POffscreenCanvas

http://github.com/heuermh/piccolo2d-processing


the game itself

http://www.ludumdare.com/compo/ludum-dare-24/?action=preview&uid=1864


and Processing

http://processing.org
```

Reported by `heuermh` on 2012-08-27 17:49:03

**Comment by heuermh** [comment]
Unable to reproduce
